[General]
loglevel = notify
dns-server = 1.1.1.1, 8.8.8.8
skip-proxy = 127.0.0.1, localhost, *.local

[Proxy]
VPN = vless, 89.125.130.93, 443, none, uuid=8247a025-355b-4a56-ac31-fdcacef79a02, security=reality, sni=www.cloudflare.com, fp=chrome, pbk=IAluGHw5WZNTeIJdbGMn4evSskVito4v8tGDVVyO610, sid=55

[Proxy Group]
PROXY = select, VPN
DIRECT = direct

[Rule]
DOMAIN-SUFFIX,gosuslugi.ru,DIRECT
DOMAIN-SUFFIX,esia.gosuslugi.ru,DIRECT
DOMAIN-SUFFIX,2gis.ru,DIRECT
GEOIP,RU,DIRECT

DOMAIN-SUFFIX,google.com,PROXY
DOMAIN-SUFFIX,youtube.com,PROXY
DOMAIN-SUFFIX,googlevideo.com,PROXY

FINAL,PROXY
