mixed-port: 7890
mode: rule

proxies:
  - name: MyVPN
    type: vless
    server: 89.125.130.93
    port: 443
    uuid: 8247a025-355b-4a56-ac31-fdcacef79a02
    tls: true
    network: tcp
    servername: www.cloudflare.com
    reality-opts:
      public-key: ВСТАВЬ_PUBLIC_KEY
      short-id: 55

rules:
  - DOMAIN-SUFFIX,gosuslugi.ru,DIRECT
  - DOMAIN-SUFFIX,esia.gosuslugi.ru,DIRECT
  - DOMAIN-SUFFIX,2gis.ru,DIRECT

  - GEOIP,RU,DIRECT

  - FINAL,PROXY
